[package]
name = "ecupool-config"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
dotenvy.workspace = true
eyre.workspace = true
serde_json.workspace = true
serde.workspace = true
tracing.workspace = true
